[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alarm-system"
version = "0.1.0"
description = "Système d'alarme pour Raspberry Pi avec serveur FastAPI"
authors = [{ name = "timsah/rmokhtar", email = "mokhtarirayan04@gmail.com" }]
requires-python = ">=3.10" #ou 3.10

dependencies = [
    "fastapi>=0.104.0",
    "uvicorn",
    "pydantic>=2.0.0",
    "python-multipart",
    "pillow", 
    "numpy>=1.21.2,<2.0",
    "opencv-python",
    "imageio[ffmpeg]",
    "ultralytics", 
    "pytoml",       
    "av"           
]

readme = "README.md"

[project.scripts]
appli = "serveur.main:lancer_serveur"


[tool.setuptools.packages.find]
where = ["."]
include = ["serveur*"]
